apiVersion: v1
kind: Service
metadata:
  name: sa-logic
spec:
  type: ClusterIP
  selector:
    app: sa-logic
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP

      
# apiVersion: v1
# kind: Service
# metadata:
#   name: sa-logic
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 5000
#   selector:
#     app: sa-logic
